# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c7497e33f40d1f469eeb998715736d54694b2e0bbadbf8a019ab6d9b4472d15cd05b5d36cbab588984070ec7cff3253d381918e1589c42fbcbddb9d8d998edc

test:
  secret_key_base: e0a2d2827c6ccadb27e9e73983dd4dec4b2b01b7a31c491a52279b68e73b21ace7956a0cb71bb481816d0c4a68652010eab86ba4837b85da342032c85bb68aff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
